name: Testing Realm Web (Pull Request)

on:
  pull_request:
    paths:
      # Only run when the PR makes changes to the packages
      - "packages/realm-web/**"
      - "packages/realm-web-integration-tests/**"
      - "packages/realm-network-transport/**"
      - "packages/realm-common/**"
      - "packages/realm-app-importer/**"
      # Changing types might also affect Realm Web
      - "types/**"
      # No need to run when updating documentation
      - "!**.md"

env:
  REALM_DISABLE_ANALYTICS: 1

jobs:
  job:
    name: Build & test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        # Ignoring scripts to prevent a prebuilt from getting fetched / built
        run: npm ci --ignore-scripts
      - name: Run unit tests
        run: npm test --workspace realm-web
      # Login with the Docker CLI to enable the integration test harness to pull the mongodb-realm-test-server
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: realm-ci
          password: ${{ secrets.REALM_CI_GITHUB_API_KEY }}
      - name: Run integration tests
        run: npm run test:github --workspace realm-web-integration-tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BAAS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BAAS_AWS_SECRET_ACCESS_KEY }}
          MONGODB_REALM_TEST_SERVER: "2023-02-22"
